#!/usr/bin/env bash
# Writes the user-supplied secret values into the Secrets Manager containers
# created by Terraform (8byte/dockerhub, 8byte/github). 8byte/db and
# 8byte/jenkins are generated by Terraform and are not touched here.
# Values come from env vars, or are prompted silently if unset. Nothing is
# echoed. Honours AWS_PROFILE / AWS_REGION like any aws cli call.
#
# Usage:
#   DOCKERHUB_USERNAME=.. DOCKERHUB_TOKEN=.. GITHUB_TOKEN=.. scripts/put-secrets.sh
#   GITHUB_TOKEN= scripts/put-secrets.sh   # explicitly empty = public repo, no prompt
#   scripts/put-secrets.sh                  # prompts for whatever is unset
set -euo pipefail

PROJECT="${PROJECT:-8byte}"
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-south-1}}"

command -v aws >/dev/null || { echo "aws cli not found" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq not found" >&2; exit 1; }

# prompt_if_unset <VAR> <label> [optional]: silent prompt when the env var is
# UNSET (an explicitly empty value is kept); empty is rejected unless the
# third argument is "optional".
prompt_if_unset() {
  local var="$1" label="$2" mode="${3:-required}"
  if [ -z "${!var+x}" ]; then
    read -r -s -p "$label: " "$var"
    printf '\n' >&2
    export "$var"
  fi
  if [ "$mode" != optional ] && [ -z "${!var}" ]; then
    echo "$var must not be empty" >&2
    exit 1
  fi
}

prompt_if_unset DOCKERHUB_USERNAME "Docker Hub username"
prompt_if_unset DOCKERHUB_TOKEN "Docker Hub access token"
prompt_if_unset GITHUB_TOKEN "GitHub PAT (repo scope; leave empty for a public repo)" optional

# A read-only Docker Hub token logs in fine and only fails at `docker push`,
# ten stages into the pipeline. Check its scope here instead: log in to the
# Hub API and read the scope claim of the JWT it returns. Any error talking
# to Docker Hub is a warning, not a failure (offline, API change).
check_dockerhub_scope() {
  local jwt payload scope
  jwt="$(curl -fsS -m 15 -X POST https://hub.docker.com/v2/users/login           -H 'Content-Type: application/json'           -d "$(jq -nc --arg u "$DOCKERHUB_USERNAME" --arg p "$DOCKERHUB_TOKEN" '{username: $u, password: $p}')"           2>/dev/null | jq -r '.token // empty')" || true
  if [ -z "$jwt" ]; then
    echo "WARNING: could not log in to Docker Hub with these credentials (bad token, or offline); continuing" >&2
    return 0
  fi
  payload="$(printf '%s' "$jwt" | cut -d. -f2 | tr '_-' '/+')"
  case $(( ${#payload} % 4 )) in 2) payload="$payload==" ;; 3) payload="$payload=" ;; esac
  scope="$(printf '%s' "$payload" | base64 -d 2>/dev/null | jq -r '.scope // empty' 2>/dev/null || true)"
  case "$scope" in
    "" | *write* | *admin* | *delete*) ;;
    *)
      echo "ERROR: the Docker Hub token has scope '$scope' and cannot push images." >&2
      echo "       Create one with 'Read & Write' at https://hub.docker.com/settings/security and re-run." >&2
      exit 1 ;;
  esac
}

# put <secret name> <json>
put() {
  local name="$1" json="$2"
  aws secretsmanager put-secret-value \
    --region "$REGION" \
    --secret-id "$name" \
    --secret-string "$json" \
    --output text --query 'VersionId' >/dev/null
  echo "wrote $name"
}

check_dockerhub_scope
put "$PROJECT/dockerhub" "$(jq -nc --arg u "$DOCKERHUB_USERNAME" --arg t "$DOCKERHUB_TOKEN" '{username: $u, token: $t}')"
put "$PROJECT/github" "$(jq -nc --arg t "$GITHUB_TOKEN" '{token: $t}')"

echo "Docker Hub and GitHub secrets written to Secrets Manager in $REGION (profile: ${AWS_PROFILE:-default})."
