#!/usr/bin/env bash
# Bootstrap for the `mon` host (monitoring track). Invoked by the Terraform
# user-data hand-off:  bash /opt/8byte/repo/scripts/bootstrap/mon.sh
# (logged to /var/log/8byte-bootstrap.log). Safe to re-run at any time.
#
# What it does:
#   1. sources /etc/8byte/env (written by user-data, see contracts.md)
#   2. reads 8byte/db and 8byte/jenkins from Secrets Manager (instance role)
#   3. writes monitoring/.env (postgres_exporter DSN, Grafana admin password,
#      SNS topic, region)
#   4. renders alertmanager/alertmanager.yml from alertmanager.yml.tpl
#   5. installs node_exporter + promtail on this host (shared helpers)
#   6. docker compose up -d for the monitoring stack and waits for readiness
set -euo pipefail

REPO_DIR="/opt/8byte/repo"
MON_DIR="${REPO_DIR}/monitoring"
ENV_FILE="/etc/8byte/env"
COMPOSE_FILE="${MON_DIR}/docker-compose.yml"
DOTENV="${MON_DIR}/.env"
AM_TPL="${MON_DIR}/alertmanager/alertmanager.yml.tpl"
AM_CFG="${MON_DIR}/alertmanager/alertmanager.yml"
STATE_DIR="/var/lib/8byte"
PROM_STATE="${STATE_DIR}/mon-prometheus-config.sha256"   # hash of prometheus.yml + rules from the last run

log()  { echo "[mon-bootstrap] $(date -u +%FT%TZ) $*"; }
die()  { log "ERROR: $*" >&2; exit 1; }

if [[ $EUID -ne 0 ]]; then
  die "must run as root"
fi

# --- 1. environment ---------------------------------------------------------
[[ -f "$ENV_FILE" ]] || die "$ENV_FILE not found (user-data should have written it)"
# shellcheck disable=SC1090
source "$ENV_FILE"
: "${ROLE:?ROLE missing from $ENV_FILE}"
: "${AWS_REGION:?AWS_REGION missing from $ENV_FILE}"
: "${SNS_TOPIC_ARN:?SNS_TOPIC_ARN missing from $ENV_FILE}"
: "${MON_PRIVATE_IP:?MON_PRIVATE_IP missing from $ENV_FILE}"
DB_SECRET_ID="${DB_SECRET_ID:-8byte/db}"
JENKINS_SECRET_ID="${JENKINS_SECRET_ID:-8byte/jenkins}"
[[ "$ROLE" == "mon" ]] || log "WARNING: ROLE=$ROLE, expected mon; continuing"
[[ -d "$MON_DIR" ]] || die "$MON_DIR not found (repo not cloned?)"

for tool in aws jq docker envsubst curl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    if [[ "$tool" == "envsubst" ]]; then
      log "installing gettext (envsubst)"
      dnf install -y -q gettext
    else
      die "required tool not found: $tool"
    fi
  fi
done
docker compose version >/dev/null 2>&1 || die "docker compose plugin not available"

log "role=$ROLE region=$AWS_REGION repo=$REPO_DIR"

# --- 2. secrets -------------------------------------------------------------
get_secret() {
  aws secretsmanager get-secret-value \
    --region "$AWS_REGION" \
    --secret-id "$1" \
    --query SecretString \
    --output text
}

log "fetching secret $DB_SECRET_ID"
db_json="$(get_secret "$DB_SECRET_ID")"
[[ -n "$db_json" && "$db_json" != "None" ]] || die "secret $DB_SECRET_ID is empty"

log "fetching secret $JENKINS_SECRET_ID"
jenkins_json="$(get_secret "$JENKINS_SECRET_ID" 2>/dev/null || true)"
[[ -n "$jenkins_json" && "$jenkins_json" != "None" ]] || jenkins_json="{}"

db_host="$(jq -r '.host // empty' <<<"$db_json")"
db_port="$(jq -r '.port // 5432' <<<"$db_json")"
db_name="$(jq -r '.dbname_prod // "todo_prod"' <<<"$db_json")"
# URL-encode user/password so characters like @ / : $ in the generated password
# survive both the URL and docker compose's env-file interpolation.
db_user_enc="$(jq -r '.username // empty | @uri' <<<"$db_json")"
db_pass_enc="$(jq -r '.password // empty | @uri' <<<"$db_json")"
[[ -n "$db_host" && -n "$db_user_enc" && -n "$db_pass_enc" ]] || die "secret $DB_SECRET_ID is missing host/username/password"

# Docker compose env-file: double-quoted values are interpolated, so escape
# backslash, double quote and $ ($$ is a literal $).
compose_quote() {
  local v="$1" bs='\'
  v="${v//"$bs"/"$bs$bs"}"
  v="${v//\"/$bs\"}"
  v="${v//\$/\$\$}"
  printf '"%s"' "$v"
}

grafana_pass="$(jq -r '.admin_password // empty' <<<"$jenkins_json")"
if [[ -n "$grafana_pass" && "$grafana_pass" != "changeme" ]]; then
  grafana_quoted="$(compose_quote "$grafana_pass")"
elif [[ -f "$DOTENV" ]] && grep -q '^GRAFANA_ADMIN_PASSWORD=' "$DOTENV"; then
  # put-secrets.sh has not run yet: keep whatever this script generated last time.
  grafana_quoted="$(sed -n 's/^GRAFANA_ADMIN_PASSWORD=//p' "$DOTENV" | head -n1)"
  log "WARNING: $JENKINS_SECRET_ID has no admin_password yet; keeping the existing Grafana password from $DOTENV"
else
  # Never start Grafana with a well-known default. Re-running this script after
  # put-secrets.sh replaces it with the Jenkins admin password.
  grafana_quoted="$(compose_quote "$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 20)")"
  log "WARNING: $JENKINS_SECRET_ID has no admin_password yet; generated a temporary Grafana password (see $DOTENV)"
fi

# --- 3. monitoring/.env -----------------------------------------------------
dotenv_content="$(cat <<DOTENV
# Generated by scripts/bootstrap/mon.sh on $(date -u +%FT%TZ). Do not edit; re-run the script.
GRAFANA_ADMIN_PASSWORD=${grafana_quoted}
PG_EXPORTER_DSN=postgresql://${db_user_enc}:${db_pass_enc}@${db_host}:${db_port}/${db_name}?sslmode=require
SNS_TOPIC_ARN=${SNS_TOPIC_ARN}
AWS_REGION=${AWS_REGION}
DOTENV
)"

# Compare without the timestamp line so an unchanged config is a no-op.
if [[ ! -f "$DOTENV" ]] || [[ "$(grep -v '^# Generated' "$DOTENV")" != "$(grep -v '^# Generated' <<<"$dotenv_content")" ]]; then
  log "writing $DOTENV"
  umask 027
  printf '%s\n' "$dotenv_content" > "$DOTENV"
  umask 022
else
  log "$DOTENV unchanged"
fi
chown root:docker "$DOTENV" 2>/dev/null || true
chmod 0640 "$DOTENV"

# --- 4. alertmanager config -------------------------------------------------
[[ -f "$AM_TPL" ]] || die "$AM_TPL not found"
rendered="$(SNS_TOPIC_ARN="$SNS_TOPIC_ARN" AWS_REGION="$AWS_REGION" envsubst '${SNS_TOPIC_ARN} ${AWS_REGION}' < "$AM_TPL")"
am_changed=0
if [[ ! -f "$AM_CFG" ]] || [[ "$(cat "$AM_CFG")" != "$rendered" ]]; then
  log "rendering $AM_CFG"
  printf '%s\n' "$rendered" > "$AM_CFG"
  am_changed=1
else
  log "$AM_CFG unchanged"
fi
chmod 0644 "$AM_CFG"

# Detect Prometheus config/rule changes since the last run (for a SIGHUP reload later).
mkdir -p "$STATE_DIR"
prom_sha="$(cat "${MON_DIR}/prometheus/prometheus.yml" "${MON_DIR}"/prometheus/rules/*.yml | sha256sum | cut -d" " -f1)"
prom_changed=0
if [[ ! -f "$PROM_STATE" ]] || [[ "$(cat "$PROM_STATE")" != "$prom_sha" ]]; then
  prom_changed=1
fi

# --- 5. host agents ---------------------------------------------------------
log "installing node_exporter"
bash "${REPO_DIR}/scripts/install-node-exporter.sh"
log "installing promtail"
bash "${REPO_DIR}/scripts/install-promtail.sh"

# --- 6. compose up ----------------------------------------------------------
systemctl is-active --quiet docker || { log "starting docker"; systemctl start docker; }

log "docker compose up -d"
docker compose -f "$COMPOSE_FILE" --env-file "$DOTENV" pull --quiet || log "WARNING: image pull had errors; continuing with local images"
docker compose -f "$COMPOSE_FILE" --env-file "$DOTENV" up -d --remove-orphans

wait_for() {
  local name="$1" url="$2" i
  for i in $(seq 1 30); do
    if curl -fsS -o /dev/null "$url"; then
      log "$name ready ($url)"
      return 0
    fi
    sleep 2
  done
  log "WARNING: $name not ready after 60 s ($url)"
  return 1
}

status=0
wait_for prometheus   http://127.0.0.1:9090/-/ready       || status=1
wait_for alertmanager http://127.0.0.1:9093/-/ready       || status=1
wait_for loki         http://127.0.0.1:3100/ready         || status=1
wait_for grafana      http://127.0.0.1:3000/api/health    || status=1
wait_for pg_exporter  http://127.0.0.1:9187/metrics       || status=1

# Prometheus/Alertmanager reload config on SIGHUP, so a re-run with changed rules
# or alertmanager.yml does not need a container restart. Only signal when
# something changed and the service is actually up.
if [[ $prom_changed -eq 1 ]]; then
  if docker compose -f "$COMPOSE_FILE" --env-file "$DOTENV" kill -s SIGHUP prometheus >/dev/null 2>&1; then
    log "prometheus config/rules changed; sent SIGHUP"
    printf '%s\n' "$prom_sha" > "$PROM_STATE"
  else
    log "WARNING: could not signal prometheus; will retry next run"
  fi
fi
if [[ $am_changed -eq 1 ]]; then
  if docker compose -f "$COMPOSE_FILE" --env-file "$DOTENV" kill -s SIGHUP alertmanager >/dev/null 2>&1; then
    log "alertmanager config changed; sent SIGHUP"
  else
    log "WARNING: could not signal alertmanager"
  fi
fi

docker compose -f "$COMPOSE_FILE" --env-file "$DOTENV" ps

if [[ $status -ne 0 ]]; then
  log "bootstrap finished with warnings; inspect: docker compose -f $COMPOSE_FILE logs"
  exit 1
fi
log "monitoring stack is up. Grafana :3000, Prometheus :9090, Alertmanager :9093, Loki :3100 (reach via SSH tunnel through management)"
